"""
mock_interview.py — AI Mock Technical Interview Engine.
Provides dynamic question banks across all career domains, real-time rubric-based evaluation,
concept verification, and model answer generation.
"""
import random
import re
import logging
from typing import Dict, List, Any

logger = logging.getLogger(__name__)

CAREER_INTERVIEW_QUESTIONS: Dict[str, List[Dict[str, Any]]] = {
    "Software Engineer": [
        {
            "id": "se_1",
            "type": "technical",
            "difficulty": "medium",
            "question": "Can you explain how a Hash Map handles collisions under the hood, and what the time complexity differences are in worst vs average case?",
            "keywords": ["collision", "chaining", "linked list", "tree", "open addressing", "o(1)", "o(n)", "hash function", "bucket"],
            "model_answer": "A Hash Map computes a hash code for a key and maps it to a bucket index. Collisions occur when multiple keys map to the same bucket. They are commonly handled via Separate Chaining (using a Linked List or Red-Black Tree in Java 8+) or Open Addressing (Linear/Quadratic Probing). The average time complexity for lookup/insert is O(1), but can degrade to O(n) in the worst case if all keys collide into a single bucket.",
        },
        {
            "id": "se_2",
            "type": "system_design",
            "difficulty": "hard",
            "question": "How would you design a scalable URL shortener service like TinyURL? What database and caching strategies would you use?",
            "keywords": ["base62", "hashing", "cache", "redis", "nosql", "scalability", "load balancer", "redirect", "sharding"],
            "model_answer": "I would use a microservices architecture with a REST API for URL encoding/decoding. URLs can be encoded using Base62 encoding on unique integer IDs generated by a distributed ID generator (e.g., Snowflake). For storage, a NoSQL database (like MongoDB or DynamoDB) or relational DB with read-replicas suits the read-heavy nature. A Redis caching layer stores high-frequency short URLs to achieve sub-millisecond 301/302 redirects.",
        },
        {
            "id": "se_3",
            "type": "behavioral",
            "difficulty": "medium",
            "question": "Describe a challenging bug you encountered in a project. How did you diagnose, debug, and prevent it from recurring?",
            "keywords": ["debug", "logs", "root cause", "unit test", "fix", "testing", "monitoring", "git"],
            "model_answer": "I isolated the issue by examining server error logs and reproducing it locally. I identified the root cause as an unhandled asynchronous race condition causing stale state updates. I resolved it with proper state locking, added comprehensive automated unit/integration tests, and added error monitoring (e.g., Sentry) to catch regressions.",
        },
    ],
    "Web Developer": [
        {
            "id": "web_1",
            "type": "technical",
            "difficulty": "medium",
            "question": "Explain the JavaScript Event Loop, Call Stack, Microtask Queue, and how Promises are scheduled.",
            "keywords": ["call stack", "event loop", "microtask", "macrotask", "promise", "settimeout", "async", "single threaded"],
            "model_answer": "JavaScript is single-threaded and executes synchronous code on the Call Stack. Asynchronous callbacks are delegated to browser APIs. When resolved, Promises enter the high-priority Microtask Queue, whereas setTimeout/setInterval enter the Macrotask Queue (Callback Queue). The Event Loop continually checks if the Call Stack is empty and drains all Microtasks before processing the next Macrotask.",
        },
        {
            "id": "web_2",
            "type": "technical",
            "difficulty": "medium",
            "question": "What is the difference between Server-Side Rendering (SSR), Client-Side Rendering (CSR), and Static Site Generation (SSG) in React/Next.js?",
            "keywords": ["ssr", "csr", "ssg", "seo", "bundle", "hydration", "performance", "html", "next.js"],
            "model_answer": "CSR renders the DOM entirely in the client browser after downloading JavaScript bundles (great for dashboards, but slower initial load and weaker SEO). SSR generates HTML on the server on each request (great for dynamic content and SEO). SSG compiles static HTML at build time (fastest CDN delivery and optimal SEO). Modern frameworks like Next.js allow hybrid rendering.",
        },
        {
            "id": "web_3",
            "type": "practical",
            "difficulty": "easy",
            "question": "How do you optimize a web application that is experiencing slow page load times?",
            "keywords": ["lazy loading", "code splitting", "compression", "cdn", "caching", "images", "webp", "lighthouse", "minification"],
            "model_answer": "I optimize web applications by: 1) Code-splitting and dynamic imports in React; 2) Optimizing images using modern formats (WebP/AVIF) and responsive sizing; 3) Enabling browser caching and CDN asset distribution; 4) Minimizing bundle size via tree shaking; and 5) Auditing performance via Google Lighthouse metrics (LCP, FID, CLS).",
        },
    ],
    "Data Scientist": [
        {
            "id": "ds_1",
            "type": "technical",
            "difficulty": "medium",
            "question": "Explain the Bias-Variance Tradeoff. How do techniques like Bagging and Boosting affect bias and variance?",
            "keywords": ["bias", "variance", "overfitting", "underfitting", "bagging", "boosting", "random forest", "xgboost"],
            "model_answer": "Bias is the error from overly simplistic assumptions (underfitting), while variance is the sensitivity to small fluctuations in training data (overfitting). The goal is to minimize total generalization error. Bagging (e.g., Random Forest) trains independent models in parallel to primarily reduce variance. Boosting (e.g., XGBoost) trains models sequentially on residual errors to reduce bias while controlling variance.",
        },
        {
            "id": "ds_2",
            "type": "technical",
            "difficulty": "hard",
            "question": "How would you handle highly imbalanced datasets when training a classification model?",
            "keywords": ["smote", "oversampling", "undersampling", "class weights", "f1 score", "precision", "recall", "roc-auc", "stratified"],
            "model_answer": "For imbalanced data: 1) Avoid raw Accuracy and use PR-AUC, F1-Score, and Confusion Matrix; 2) Apply resampling techniques like SMOTE (Synthetic Minority Over-sampling) or Tomek links; 3) Use cost-sensitive learning by adjusting class weights in the loss function; and 4) Use Stratified K-Fold cross-validation to preserve class distributions during evaluation.",
        },
        {
            "id": "ds_3",
            "type": "practical",
            "difficulty": "medium",
            "question": "Walk me through your end-to-end process for building and evaluating a Machine Learning pipeline.",
            "keywords": ["eda", "cleaning", "feature engineering", "scaling", "train test split", "cross validation", "metrics", "deployment"],
            "model_answer": "1) Problem formulation and metric definition; 2) Exploratory Data Analysis (EDA) and cleaning (handling missing values, outliers); 3) Feature engineering and transformations (encoding, scaling); 4) Baseline model creation and hyperparameter tuning with cross-validation; 5) Rigorous evaluation on unseen test data; and 6) Exporting artefacts for production deployment with drift monitoring.",
        },
    ],
    "Cloud Engineer": [
        {
            "id": "cloud_1",
            "type": "technical",
            "difficulty": "medium",
            "question": "Explain the difference between horizontal and vertical scaling in cloud architecture, and when you would choose each.",
            "keywords": ["horizontal", "vertical", "auto scaling", "load balancer", "stateless", "resources", "availability", "distributed"],
            "model_answer": "Vertical scaling (scaling up) increases compute resources (CPU/RAM) of an existing instance, but has hardware limits and single-point-of-failure risks. Horizontal scaling (scaling out) adds more instance nodes behind a Load Balancer. In cloud computing, horizontal scaling with stateless microservices and Auto Scaling Groups is preferred for high availability and fault tolerance.",
        },
        {
            "id": "cloud_2",
            "type": "system_design",
            "difficulty": "hard",
            "question": "How do you design a secure Virtual Private Cloud (VPC) on AWS with public and private subnets?",
            "keywords": ["vpc", "public subnet", "private subnet", "nat gateway", "internet gateway", "security group", "nacl", "bastion"],
            "model_answer": "Create a VPC with public and private subnets across multiple Availability Zones. Public subnets route through an Internet Gateway (IGW) hosting Load Balancers. Private subnets host application servers and databases with no direct internet access, routing outbound traffic through a NAT Gateway. Security Groups act as stateful instance firewalls and Network ACLs serve as stateless subnet boundaries.",
        },
    ],
    "Cybersecurity Analyst": [
        {
            "id": "sec_1",
            "type": "technical",
            "difficulty": "medium",
            "question": "Explain the difference between Symmetric and Asymmetric encryption. What is a practical scenario where both are used together?",
            "keywords": ["symmetric", "asymmetric", "aes", "rsa", "public key", "private key", "tls", "ssl", "handshake", "hybrid"],
            "model_answer": "Symmetric encryption (e.g., AES) uses the same secret key for encryption and decryption (very fast). Asymmetric encryption (e.g., RSA/ECC) uses a Public Key for encryption and Private Key for decryption (slower but solves key distribution). In HTTPS/TLS handshakes, asymmetric encryption securely exchanges a session key, and then fast symmetric encryption encrypts the actual data stream.",
        },
        {
            "id": "sec_2",
            "type": "technical",
            "difficulty": "medium",
            "question": "What is SQL Injection (SQLi), and how do you completely prevent it in modern applications?",
            "keywords": ["sql injection", "parameterized queries", "prepared statements", "orm", "input validation", "sanitization", "least privilege"],
            "model_answer": "SQL Injection occurs when untrusted user input is directly concatenated into a dynamic SQL statement, allowing attackers to manipulate database queries. It is completely prevented by using Parameterized Queries (Prepared Statements) or secure ORMs (like SQLAlchemy/Hibernate), enforcing strict input validation, and configuring database users with least-privilege permissions.",
        },
    ],
    "AI/ML Engineer": [
        {
            "id": "ai_1",
            "type": "technical",
            "difficulty": "hard",
            "question": "What is Retrieval-Augmented Generation (RAG), and how does it prevent LLM hallucination in enterprise applications?",
            "keywords": ["rag", "retrieval", "embeddings", "vector database", "hallucination", "context", "llm", "chunking", "similarity search"],
            "model_answer": "RAG enhances Large Language Models by retrieving relevant domain-specific documents from an external Vector Database (using embedding similarity search) and injecting them into the LLM context prompt. This ensures answers are grounded in verifiable, proprietary facts rather than static training memory, dramatically reducing hallucinations.",
        },
        {
            "id": "ai_2",
            "type": "technical",
            "difficulty": "medium",
            "question": "Explain how Gradient Descent works and why Adam optimizer is widely used in Deep Learning.",
            "keywords": ["gradient descent", "learning rate", "loss function", "adam", "momentum", "adaptive", "rmsprop", "backpropagation"],
            "model_answer": "Gradient Descent iteratively adjusts neural network weights in the direction opposite to the gradient of the loss function to minimize error. The Adam (Adaptive Moment Estimation) optimizer combines Momentum (exponential moving average of gradients) and RMSprop (adaptive learning rates per parameter), leading to fast convergence and stability across sparse gradients.",
        },
    ],
    "DevOps Engineer": [
        {
            "id": "devops_1",
            "type": "technical",
            "difficulty": "medium",
            "question": "What is the difference between Docker and Kubernetes? How do they work together in a CI/CD pipeline?",
            "keywords": ["docker", "kubernetes", "container", "orchestration", "pods", "ci/cd", "deployment", "scaling", "cluster"],
            "model_answer": "Docker package applications and their dependencies into lightweight, portable containers. Kubernetes is a container orchestrator that manages the deployment, auto-scaling, self-healing, and networking of multiple containers across a cluster. In CI/CD, the CI pipeline builds and tests a Docker image and pushes to a registry, while the CD pipeline deploys the image to Kubernetes manifests.",
        },
    ],
    "Data Analyst": [
        {
            "id": "da_1",
            "type": "technical",
            "difficulty": "medium",
            "question": "Explain SQL Window Functions (e.g., ROW_NUMBER, RANK, DENSE_RANK, OVER, PARTITION BY) and when you use them over standard GROUP BY.",
            "keywords": ["window functions", "partition by", "row_number", "rank", "dense_rank", "group by", "aggregation", "cumulative"],
            "model_answer": "Window functions perform calculations across a set of table rows related to the current row without collapsing the rows into a single summary output like GROUP BY. Using OVER(PARTITION BY ... ORDER BY ...), we calculate running totals, moving averages, and rankings (where ROW_NUMBER gives sequential ints, RANK skips ranks on ties, and DENSE_RANK does not skip).",
        },
    ],
}


def get_questions_for_career(career: str, count: int = 3) -> List[Dict[str, Any]]:
    """Retrieve curated, role-specific interview questions with fallback matching."""
    career_clean = career.strip()
    questions = CAREER_INTERVIEW_QUESTIONS.get(career_clean)

    if not questions:
        for k, v in CAREER_INTERVIEW_QUESTIONS.items():
            if k.lower() in career_clean.lower() or career_clean.lower() in k.lower():
                questions = v
                break

    if not questions:
        questions = CAREER_INTERVIEW_QUESTIONS["Software Engineer"]

    shuffled = list(questions)
    random.shuffle(shuffled)
    return shuffled[:count]


def evaluate_student_answer(question: str, expected_keywords: List[str], model_answer: str, user_answer: str) -> Dict[str, Any]:
    """
    Rigorously evaluate student answer based on keyword concepts, vocabulary diversity, and technical accuracy.
    """
    clean_ans = user_answer.strip().lower()
    raw_words = re.findall(r"\b[a-z0-9\(\)\-\_]+\b", clean_ans)

    if len(raw_words) < 4:
        return {
            "score": 10,
            "clarity_score": 15,
            "strengths": [],
            "missing_concepts": expected_keywords[:4],
            "feedback": "Answer is too brief or empty. Please explain the technical mechanisms and provide concrete examples.",
            "model_answer": model_answer,
        }

    # 1. Repetition and gibberish check
    unique_words = set(raw_words)
    diversity_ratio = len(unique_words) / len(raw_words)

    # 2. Count matched technical keywords
    matched_keywords = []
    missing_keywords = []
    for kw in expected_keywords:
        kw_clean = kw.lower()
        if re.search(r"\b" + re.escape(kw_clean) + r"\b", clean_ans):
            matched_keywords.append(kw)
        elif kw_clean in clean_ans:
            matched_keywords.append(kw)
        else:
            missing_keywords.append(kw)

    num_matched = len(matched_keywords)
    total_expected = max(len(expected_keywords), 1)
    keyword_ratio = num_matched / total_expected

    # 3. Calculate Real Score strictly based on technical accuracy
    if diversity_ratio < 0.4:
        # High word repetition / mic loop detected
        total_score = max(5, round(num_matched * 8))
        clarity_score = 15
        feedback = "The answer contains repeated fragments and unclear speech. Practice delivering concise, structured technical points."
        strengths = [f"Mentioned {kw}" for kw in matched_keywords[:2]] if matched_keywords else []
    elif num_matched == 0:
        # Zero required technical concepts matched
        total_score = 12
        clarity_score = 25
        strengths = []
        feedback = "The response did not address the core technical mechanisms required for this question. Review the ideal model answer below."
    elif num_matched == 1:
        # Only 1 keyword
        total_score = 28
        clarity_score = 45
        strengths = [f"Mentioned related concept: '{matched_keywords[0]}'."]
        feedback = f"Partial response. You mentioned '{matched_keywords[0]}', but missed critical details like {', '.join(missing_keywords[:2])}."
    elif num_matched == 2:
        total_score = 52
        clarity_score = 65
        strengths = [f"Covered basic principles: {', '.join(matched_keywords)}."]
        feedback = f"Good initial direction. To score higher, explain the step-by-step mechanism and address {', '.join(missing_keywords[:2])}."
    elif num_matched == 3:
        total_score = 74
        clarity_score = 80
        strengths = [f"Solid explanation covering {', '.join(matched_keywords)}."]
        feedback = "Strong technical answer! You covered the primary concepts and showed good understanding."
    elif num_matched >= 4:
        total_score = min(96, 85 + (num_matched * 3))
        clarity_score = 92
        strengths = [
            f"Thoroughly explained key concepts: {', '.join(matched_keywords[:4])}.",
            "Demonstrated strong architectural understanding and precise terminology.",
        ]
        feedback = "Outstanding response! Structured, technically accurate, and ready for Tier-1 engineering interviews."
    else:
        total_score = 50
        clarity_score = 60
        strengths = [f"Touched upon: {', '.join(matched_keywords)}."]
        feedback = "Good attempt. Expand on specific trade-offs and edge cases."

    return {
        "score": total_score,
        "clarity_score": clarity_score,
        "strengths": strengths,
        "missing_concepts": missing_keywords[:3] if missing_keywords else [],
        "feedback": feedback,
        "model_answer": model_answer,
    }
